<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name'           => 'Bleu de Chanel',
                'brand'          => 'Chanel',
                'description'    => 'A woody aromatic fragrance for the man who defies convention.',
                'category'       => 'Eau de Parfum',
                'gender'         => 'male',
                'price'          => 185.00,
                'discount_price' => null,
                'stock'          => 42,
                'size'           => '100ml',
                'notes'          => ['top' => 'Citrus', 'middle' => 'Ginger', 'base' => 'Sandalwood'],
                'images'         => ['https://placehold.co/400x400?text=Bleu+de+Chanel'],
                'rating'         => 4.80,
                'review_count'   => 320,
                'is_featured'    => true,
                'is_active'      => true,
            ],
            [
                'name'           => 'Black Opium',
                'brand'          => 'Yves Saint Laurent',
                'description'    => 'Addictive and energising. A feminine fragrance with a rock twist.',
                'category'       => 'Eau de Parfum',
                'gender'         => 'female',
                'price'          => 145.00,
                'discount_price' => 120.00,
                'stock'          => 28,
                'size'           => '90ml',
                'notes'          => ['top' => 'Coffee', 'middle' => 'Jasmine', 'base' => 'Vanilla'],
                'images'         => ['https://placehold.co/400x400?text=Black+Opium'],
                'rating'         => 4.70,
                'review_count'   => 215,
                'is_featured'    => true,
                'is_active'      => true,
            ],
            [
                'name'           => 'Sauvage',
                'brand'          => 'Dior',
                'description'    => 'A raw and noble ingredient inspired by wide open spaces.',
                'category'       => 'Eau de Toilette',
                'gender'         => 'male',
                'price'          => 160.00,
                'discount_price' => null,
                'stock'          => 55,
                'size'           => '100ml',
                'notes'          => ['top' => 'Bergamot', 'middle' => 'Pepper', 'base' => 'Ambroxan'],
                'images'         => ['https://placehold.co/400x400?text=Sauvage'],
                'rating'         => 4.90,
                'review_count'   => 512,
                'is_featured'    => true,
                'is_active'      => true,
            ],
            [
                'name'           => 'Coco Mademoiselle',
                'brand'          => 'Chanel',
                'description'    => 'An oriental fresh fragrance. Assertive and sensual.',
                'category'       => 'Eau de Parfum',
                'gender'         => 'female',
                'price'          => 175.00,
                'discount_price' => 150.00,
                'stock'          => 18,
                'size'           => '100ml',
                'notes'          => ['top' => 'Orange', 'middle' => 'Rose', 'base' => 'Patchouli'],
                'images'         => ['https://placehold.co/400x400?text=Coco+Mademoiselle'],
                'rating'         => 4.75,
                'review_count'   => 430,
                'is_featured'    => false,
                'is_active'      => true,
            ],
            [
                'name'           => 'Acqua di Gio',
                'brand'          => 'Giorgio Armani',
                'description'    => 'Inspired by the natural elements of sun, sea and earth.',
                'category'       => 'Eau de Toilette',
                'gender'         => 'male',
                'price'          => 130.00,
                'discount_price' => null,
                'stock'          => 0,
                'size'           => '100ml',
                'notes'          => ['top' => 'Sea Notes', 'middle' => 'Jasmine', 'base' => 'Musk'],
                'images'         => ['https://placehold.co/400x400?text=Acqua+di+Gio'],
                'rating'         => 4.60,
                'review_count'   => 290,
                'is_featured'    => false,
                'is_active'      => true,
            ],
            [
                'name'           => 'La Vie Est Belle',
                'brand'          => 'Lancôme',
                'description'    => 'A feminine fragrance that celebrates happiness and freedom.',
                'category'       => 'Eau de Parfum',
                'gender'         => 'female',
                'price'          => 140.00,
                'discount_price' => 115.00,
                'stock'          => 33,
                'size'           => '75ml',
                'notes'          => ['top' => 'Blackcurrant', 'middle' => 'Iris', 'base' => 'Praline'],
                'images'         => ['https://placehold.co/400x400?text=La+Vie+Est+Belle'],
                'rating'         => 4.65,
                'review_count'   => 178,
                'is_featured'    => true,
                'is_active'      => true,
            ],
            [
                'name'           => 'Oud Wood',
                'brand'          => 'Tom Ford',
                'description'    => 'Rare oud wood blended with sandalwood and vetiver.',
                'category'       => 'Eau de Parfum',
                'gender'         => 'unisex',
                'price'          => 320.00,
                'discount_price' => null,
                'stock'          => 12,
                'size'           => '50ml',
                'notes'          => ['top' => 'Oud', 'middle' => 'Rosewood', 'base' => 'Vetiver'],
                'images'         => ['https://placehold.co/400x400?text=Oud+Wood'],
                'rating'         => 4.85,
                'review_count'   => 95,
                'is_featured'    => true,
                'is_active'      => true,
            ],
            [
                'name'           => 'Light Blue',
                'brand'          => 'Dolce & Gabbana',
                'description'    => 'Fresh and clean fragrance inspired by the Sicilian summer.',
                'category'       => 'Eau de Toilette',
                'gender'         => 'unisex',
                'price'          => 110.00,
                'discount_price' => 89.00,
                'stock'          => 47,
                'size'           => '100ml',
                'notes'          => ['top' => 'Sicilian Lemon', 'middle' => 'Bamboo', 'base' => 'Musk'],
                'images'         => ['https://placehold.co/400x400?text=Light+Blue'],
                'rating'         => 4.55,
                'review_count'   => 340,
                'is_featured'    => false,
                'is_active'      => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
